### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by paulidale** [DC23/rpgg-random-experience-2022#2]
If the tables were plain text files (and the tex automatically generated), they'd be easy to use for other things: e.g. a program that generates random results from them.

**Comment by DC23** [comment]
would you just use \input{} to insert the text into the tex file? How would that handle markup around the sub-table references?

**Comment by paulidale** [comment]
I'd write a program to output the tex :)

**Comment by DC23** [comment]
I did think of writing a quick Python script to do that. Then you could probably get the container that builds the PDF in an Action to run the script as well. The Makefile could still be used when working locally.

**Comment by paulidale** [comment]
The Action can absolutely do that.

However, I'd suggest adding the relevant commands to do the conversion to the Makefile.  I.e. make a local build exactly the same as the Actions build.

**Comment by DC23** [comment]
That's what I was thinking, have the Makefile do the full build, and the Action container runs make.

If it's not obvious, I took the laziest approach to minimise up-front effort on this rather than building a decent system.
