### ISSUE TITLE
Compile PDFs as GitHub Action rather than manually before pushing code.

### ISSUE THREAD

**Issue by DC23** [DC23/rpgg-random-experience-2022#3]
https://github.com/xu-cheng/texlive-action would probably work.

The Makefile would be retained for use while working on the tables.

**Comment by paulidale** [comment]
Checking out the code and running make would also work.  I've done a bit with actions as part of my work on OpenSSL.

**Comment by DC23** [comment]
Closing this issue. This task is being done in #2
